### ISSUE TITLE
About the single view input images in 3D tasks

### ISSUE THREAD

**Issue by cocoshe** [TangYuan96/MiniGPT-3D#2]
Hi! Thanks for your great work, I have a question about the single view input images in 3D tasks.

I want to ask how to choose and get the "input single view image" when evaluating on 3D tasks? I think it shouldn't be random.
![image](https://github.com/user-attachments/assets/18032f88-2a47-43ae-bd69-a3675b3716f3)

**Comment by TangYuan96** [comment]
Thanks for your interest in our work！！

Actually, all results of 2D-LLM baseline methods  in our paper  are just  from  [PointLLM](https://github.com/OpenRobotLab/PointLLM) 

1. **how to get single view image of point cloud**

You can use this code to try to get single view image  of given point cloud.

```python
import os
import open3d as o3d
import numpy as np


def rotate_points_around_x_axis(points, angle_degrees):
    
    angle_radians = np.radians(angle_degrees)


    rotation_matrix = np.array([
        [1, 0, 0],
        [0, np.cos(angle_radians), -np.sin(angle_radians)],
        [0, np.sin(angle_radians), np.cos(angle_radians)]
    ])


    xyz = points[:, :3]


    rotated_xyz = np.dot(xyz, rotation_matrix)


    rotated_points = np.hstack((rotated_xyz, points[:, 3:]))

    return rotated_points


def pc_normalize(pc):
    """
    pc: Nx3 array
    This functions normalizes a point cloud to fit within a unit sphere.
    It first calculates the centroid of the point cloud and then subtracts
    it from all points before scaling all points to fit within a unit sphere.
    """
    centroid = np.mean(pc, axis=0)
    pc = pc - centroid
    m = np.max(np.sqrt(np.sum(pc**2, axis=1)))
    pc = pc / m
    return pc


def render_img(points, save_img_path):


    # set each point size
    point_size_set = 3  

    points = rotate_points_around_x_axis(points, angle_degrees=90)


    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points[:, :3])

    pcd.colors = o3d.utility.Vector3dVector(points[:, 3:])

    vis = o3d.visualization.Visualizer()
    vis.create_window()

    opt = vis.get_render_option()
    opt.point_size = point_size_set

    vis.add_geometry(pcd)

    vis.update_geometry(pcd)
    # Capture the image
    vis.poll_events()
    vis.update_renderer()
    vis.capture_screen_image(save_img_path)




if __name__ == '__main__':


    filepath = 'test.npy'

    save_img_path = "test_render.jpg"

    pc  = np.load(filepath)  # N,6

    render_img(pc, save_img_path)

```
2. **how to choose the single view image**

During the evaluation process, it is not practical to select the best projection angle for each test point cloud.

Therefore, when converting 3D point clouds to single images in batches, only a fixed projection setting can be selected.

2D-LLM uses the 2D information of the projected image to understand the 3D point cloud, which must lose the 3D geometric information, resulting in poor performance on 3D tasks.

However, 3D-LLM has no view limit, it can directly understand the 3D information by the original point cloud data

I hope these can answer your concerns.
﻿

**Comment by cocoshe** [comment]
> Thanks for your interest in our work！！
> 
> Actually, all results of 2D-LLM baseline methods in our paper are just from [PointLLM](https://github.com/OpenRobotLab/PointLLM)
> 
> 1. **how to get single view image of point cloud**
> 
> You can use this code to try to get single view image of given point cloud.
> 
> ```python
> import os
> import open3d as o3d
> import numpy as np
> 
> 
> def rotate_points_around_x_axis(points, angle_degrees):
>     
>     angle_radians = np.radians(angle_degrees)
> 
> 
>     rotation_matrix = np.array([
>         [1, 0, 0],
>         [0, np.cos(angle_radians), -np.sin(angle_radians)],
>         [0, np.sin(angle_radians), np.cos(angle_radians)]
>     ])
> 
> 
>     xyz = points[:, :3]
> 
> 
>     rotated_xyz = np.dot(xyz, rotation_matrix)
> 
> 
>     rotated_points = np.hstack((rotated_xyz, points[:, 3:]))
> 
>     return rotated_points
> 
> 
> def pc_normalize(pc):
>     """
>     pc: Nx3 array
>     This functions normalizes a point cloud to fit within a unit sphere.
>     It first calculates the centroid of the point cloud and then subtracts
>     it from all points before scaling all points to fit within a unit sphere.
>     """
>     centroid = np.mean(pc, axis=0)
>     pc = pc - centroid
>     m = np.max(np.sqrt(np.sum(pc**2, axis=1)))
>     pc = pc / m
>     return pc
> 
> 
> def render_img(points, save_img_path):
> 
> 
>     # set each point size
>     point_size_set = 3  
> 
>     points = rotate_points_around_x_axis(points, angle_degrees=90)
> 
> 
>     pcd = o3d.geometry.PointCloud()
>     pcd.points = o3d.utility.Vector3dVector(points[:, :3])
> 
>     pcd.colors = o3d.utility.Vector3dVector(points[:, 3:])
> 
>     vis = o3d.visualization.Visualizer()
>     vis.create_window()
> 
>     opt = vis.get_render_option()
>     opt.point_size = point_size_set
> 
>     vis.add_geometry(pcd)
> 
>     vis.update_geometry(pcd)
>     # Capture the image
>     vis.poll_events()
>     vis.update_renderer()
>     vis.capture_screen_image(save_img_path)
> 
> 
> 
> 
> if __name__ == '__main__':
> 
> 
>     filepath = 'test.npy'
> 
>     save_img_path = "test_render.jpg"
> 
>     pc  = np.load(filepath)  # N,6
> 
>     render_img(pc, save_img_path)
> ```
> 
> 2. **how to choose the single view image**
> 
> During the evaluation process, it is not practical to select the best projection angle for each test point cloud.
> 
> Therefore, when converting 3D point clouds to single images in batches, only a fixed projection setting can be selected.
> 
> 2D-LLM uses the 2D information of the projected image to understand the 3D point cloud, which must lose the 3D geometric information, resulting in poor performance on 3D tasks.
> 
> However, 3D-LLM has no view limit, it can directly understand the 3D information by the original point cloud data
> 
> I hope these can answer your concerns.

Thanks for you reply, that really helps! Thanks for your great work again~
