### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by yfcharm** [TangYuan96/MiniGPT-3D#4]
Thanks for your awesome work! I wonder if you have any plan to release your code. Can you offer a schedule for us to refer?

**Comment by TangYuan96** [comment]
Thanks for your interest in our work.

We apologize for the delay as we were occupied with other project in the past few months.
 
The codes and weights for MiniGPT-3D have now been organized and will be released following final testing, expected this week.

**Comment by yfcharm** [comment]
Thanks for your reply. Looking forward to your latest release.

**Comment by hangpengjie** [comment]
Looking forward to code release.

**Comment by TangYuan96** [comment]
Sorry for late，the codes and model weights have been released.  Check it out!!!
